variables:
  UNITY_EXECUTABLE_PATH_MAC: "/Applications/Unity-2c0750f9d615/Unity.app/Contents/MacOS/Unity"
  UNITY_EXECUTABLE_PATH_LINUX: "/home/builduser/buildslave/unity/build/build/LinuxEditor/Unity"
  UNITY_EXECUTABLE_PATH_WINDOWS: "C:/Program Files/Unity-2c0750f9d615/Editor/Unity.exe"

stages:
  - test
  - build
  - run

mac:boids:mono:build:
  stage: build
  tags:
    - macOS
  script:
    - dotnet ~/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable $UNITY_EXECUTABLE_PATH_MAC -projectpath ECSJobDemos -batchmode -buildOSXUniversalPlayer build/mono/macos-standalone.app -nographics -silentcrashes -automated -logfile output-macos-boids-build-mono.log -quit -scene Assets/BoidExample.unity -scriptingBackend mono -displayResolutionDialog disabled
  artifacts:
    name: "artifacts-macos-boids"
    when: always
    paths:
      - "*.log"
      - "*.xml"
      - "ECSJobDemos/build/"
    expire_in: 1 week

mac:boids:il2cpp:build:
  stage: build
  tags:
    - macOS
  script:
    - dotnet ~/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable $UNITY_EXECUTABLE_PATH_MAC -projectpath ECSJobDemos -batchmode -buildOSXUniversalPlayer build/il2cpp/macos-standalone.app -nographics -silentcrashes -automated -logfile output-macos-boids-build-il2cpp.log -quit -scene Assets/BoidExample.unity -scriptingBackend il2cpp -displayResolutionDialog disabled
  artifacts:
    name: "artifacts-macos-boids"
    when: always
    paths:
      - "*.log"
      - "*.xml"
      - "ECSJobDemos/build/"
    expire_in: 1 week

mac:boids:mono:run:
  stage: run
  tags:
    - macOS
  script:
    - dotnet ~/unity-log-wrapper/UnityLauncher.Player/bin/Debug/netcoreapp2.0/UnityLauncher.Player.dll -executable ECSJobDemos/build/mono/macos-standalone.app/Contents/MacOS/macos-standalone -logfile output-macos-boids-run-mono.log -timeout 120 -timeoutIgnore
  artifacts:
    name: "artifacts-macos-boids"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week
  dependencies:
    - mac:boids:mono:build

mac:boids:il2cpp:run:
  stage: run
  tags:
    - macOS
  script:
    - dotnet ~/unity-log-wrapper/UnityLauncher.Player/bin/Debug/netcoreapp2.0/UnityLauncher.Player.dll -executable ECSJobDemos/build/il2cpp/macos-standalone.app/Contents/MacOS/macos-standalone -logfile output-macos-boids-run-il2cpp.log -timeout 120 -timeoutIgnore
  artifacts:
    name: "artifacts-macos-boids"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week
  dependencies:
    - mac:boids:il2cpp:build

mac:test:
  stage: test
  tags:
    - macOS
  script:
    - dotnet ~/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable $UNITY_EXECUTABLE_PATH_MAC -projectpath $(pwd)/ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output-macos-test.log -runtests -testresults results.xml
  artifacts:
    name: "artifacts-macos-test"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week

win:boids:mono:build:
  stage: build
  tags:
    - windows
  script:
    - dotnet C:/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable "%UNITY_EXECUTABLE_PATH_WINDOWS%" -projectpath ECSJobDemos -batchmode -buildWindows64Player build/mono/windows-standalone.exe -nographics -silentcrashes -automated -logfile output-win-boids-build-mono.log -quit -scene Assets/BoidExample.unity -scriptingBackend mono -displayResolutionDialog disabled
  artifacts:
    name: "artifacts-win-boids"
    when: always
    paths:
      - "*.log"
      - "*.xml"
      - "ECSJobDemos/build/"
    expire_in: 1 week

win:boids:il2cpp:build:
  stage: build
  tags:
    - windows
  script:
    - dotnet C:/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable "%UNITY_EXECUTABLE_PATH_WINDOWS%" -projectpath ECSJobDemos -batchmode -buildWindows64Player build/il2cpp/windows-standalone.exe -nographics -silentcrashes -automated -logfile output-win-boids-build-il2cpp.log -quit -scene Assets/BoidExample.unity -scriptingBackend il2cpp -displayResolutionDialog disabled
  artifacts:
    name: "artifacts-win-boids"
    when: always
    paths:
      - "*.log"
      - "*.xml"
      - "ECSJobDemos/build/"
    expire_in: 1 week

win:boids:mono:run:
  stage: run
  tags:
    - windows
  script:
    - dotnet C:/unity-log-wrapper/UnityLauncher.Player/bin/Debug/netcoreapp2.0/UnityLauncher.Player.dll -executable ECSJobDemos/build/mono/windows-standalone.exe -logfile output-win-boids-run-mono.log -timeout 120 -timeoutIgnore
  artifacts:
    name: "artifacts-win-boids"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week
  dependencies:
    - win:boids:mono:build

win:boids:il2cpp:run:
  stage: run
  tags:
    - windows
  script:
    - dotnet C:/unity-log-wrapper/UnityLauncher.Player/bin/Debug/netcoreapp2.0/UnityLauncher.Player.dll -executable ECSJobDemos/build/il2cpp/windows-standalone.exe -logfile output-win-boids-run-il2cpp.log -timeout 120 -timeoutIgnore
  artifacts:
    name: "artifacts-win-boids"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week
  dependencies:
    - win:boids:il2cpp:build

win:test:
  stage: test
  tags:
    - windows
  script:
    - dotnet C:/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable "%UNITY_EXECUTABLE_PATH_WINDOWS%" -projectpath ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output-win-test.log -runtests -testresults results.xml
  artifacts:
    name: "artifacts-win-test"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week

#build:linux:
#  stage: build
#  allow_failure: true
#  tags:
#    - linux
#  script:
#    - dotnet ~/unity-log-wrapper/bin/Debug/netcoreapp2.0/UnityLogWrapper.dll -unityexecutable $UNITY_EXECUTABLE_PATH_LINUX -projectpath $(pwd)/ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output.log -quit
#  artifacts:
#      name: "linux-build-logs"
#      when: always
#      paths:
#        - "*.log"
#        - "*.xml"
#      expire_in: 1 week

#standalone:linux:
#  stage: standalone
#  allow_failure: true
#  tags:
#    - linux
#  script:
#    - dotnet ~/unity-log-wrapper/bin/Debug/netcoreapp2.0/UnityLogWrapper.dll -unityexecutable $UNITY_EXECUTABLE_PATH_LINUX -projectpath $(pwd)/ECSJobDemos -batchmode -buildLinuxUniversalPlayer build/linux-standalone -silentcrashes -automated -logfile output.log -quit
#  artifacts:
#      name: "linux-standalone-logs"
#      when: always
#      paths:
#        - "*.log"
#        - "*.xml"
#        - "ECSJobDemos/build/"
#      expire_in: 1 week

#test:linux:
#  stage: test
#  allow_failure: true
#  tags:
#    - linux
#  script:
#    - dotnet ~/unity-log-wrapper/bin/Debug/netcoreapp2.0/UnityLogWrapper.dll -unityexecutable $UNITY_EXECUTABLE_PATH_LINUX -projectpath $(pwd)/ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output.log -runtests -testresults results.xml
#  artifacts:
#    name: "linux-test-logs"
#    when: always
#    paths:
#      - "*.log"
#      - "*.xml"
#    expire_in: 1 week
