variables:
  UNITY_EXECUTABLE_PATH_MAC: "/Applications/Unity-966b48dc5f14/Unity.app/Contents/MacOS/Unity"
  UNITY_EXECUTABLE_PATH_LINUX: "/home/builduser/buildslave/unity/build/build/LinuxEditor/Unity"
  UNITY_EXECUTABLE_PATH_WINDOWS: "C:/Program Files/Unity-966b48dc5f14/Editor/Unity.exe"

stages:
  - build
  - standalone
  - test

build:macOS:
  stage: build
  tags:
    - macOS
  script:
    - dotnet ~/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable $UNITY_EXECUTABLE_PATH_MAC -projectpath $(pwd)/ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output.log -quit
  artifacts:
    name: "mac-build-logs"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week

standalone:boids:macOS:
  stage: standalone
  tags:
    - macOS
  script:
    - echo BUILDING MONO
    - dotnet ~/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable $UNITY_EXECUTABLE_PATH_MAC -projectpath ECSJobDemos -batchmode -buildOSXUniversalPlayer build/mono/macos-standalone.exe -nographics -silentcrashes -automated -logfile output-build-mono.log -quit -scene Assets/BoidExample.unity -scriptingBackend mono -displayResolutionDialog disabled
    - echo RUNNING MONO
    - dotnet ~/unity-log-wrapper/UnityLauncher.Player/bin/Debug/netcoreapp2.0/UnityLauncher.Player.dll -executable ECSJobDemos/build/mono/macos-standalone.exe -logfile output-run-mono.log -timeout 60 -timeoutIgnore
    - echo BUILDING IL2CPP
    - dotnet ~/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable $UNITY_EXECUTABLE_PATH_MAC -projectpath ECSJobDemos -batchmode -buildOSXUniversalPlayer build/il2cpp/macos-standalone.exe -nographics -silentcrashes -automated -logfile output-build-il2cpp.log -quit -scene Assets/BoidExample.unity -scriptingBackend il2cpp -displayResolutionDialog disabled
    - echo RUNNING IL2CPP
    - dotnet ~/unity-log-wrapper/UnityLauncher.Player/bin/Debug/netcoreapp2.0/UnityLauncher.Player.dll -executable ECSJobDemos/build/il2cpp/macos-standalone.exe -logfile output-run-il2cpp.log -timeout 60 -timeoutIgnore
  artifacts:
    name: "mac-standalone-logs"
    when: always
    paths:
      - "*.log"
      - "*.xml"
      - "ECSJobDemos/build/"
    expire_in: 1 week

test:macOS:
  stage: test
  tags:
    - macOS
  script:
    - dotnet ~/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable $UNITY_EXECUTABLE_PATH_MAC -projectpath $(pwd)/ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output.log -runtests -testresults results.xml
  artifacts:
    name: "mac-test-logs"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week

build:windows:
  stage: build
  tags:
    - windows
  script:
    - dotnet C:/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable "%UNITY_EXECUTABLE_PATH_WINDOWS%" -projectpath ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output.log -quit
  artifacts:
    name: "windows-build-logs"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week

standalone:boids:windows:
  stage: standalone
  tags:
    - windows
  script:
    - echo BUILDING MONO
    - dotnet C:/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable "%UNITY_EXECUTABLE_PATH_WINDOWS%" -projectpath ECSJobDemos -batchmode -buildWindows64Player build/mono/windows-standalone.exe -nographics -silentcrashes -automated -logfile output-build-mono.log -quit -scene Assets/BoidExample.unity -scriptingBackend mono -displayResolutionDialog disabled
    - echo RUNNING MONO
    - dotnet C:/unity-log-wrapper/UnityLauncher.Player/bin/Debug/netcoreapp2.0/UnityLauncher.Player.dll -executable ECSJobDemos/build/mono/windows-standalone.exe -logfile output-run-mono.log -timeout 60 -timeoutIgnore
    - echo BUILDING IL2CPP
    - dotnet C:/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable "%UNITY_EXECUTABLE_PATH_WINDOWS%" -projectpath ECSJobDemos -batchmode -buildWindows64Player build/il2cpp/windows-standalone.exe -nographics -silentcrashes -automated -logfile output-build-il2cpp.log -quit -scene Assets/BoidExample.unity -scriptingBackend il2cpp -displayResolutionDialog disabled
    - echo RUNNING IL2CPP
    - dotnet C:/unity-log-wrapper/UnityLauncher.Player/bin/Debug/netcoreapp2.0/UnityLauncher.Player.dll -executable ECSJobDemos/build/il2cpp/windows-standalone.exe -logfile output-run-il2cpp.log -timeout 60 -timeoutIgnore
  artifacts:
    name: "windows-standalone-logs"
    when: always
    paths:
      - "*.log"
      - "*.xml"
      - "ECSJobDemos/build/"
    expire_in: 1 week

test:windows:
  stage: test
  tags:
    - windows
  script:
    - dotnet C:/unity-log-wrapper/UnityLauncher.Editor/bin/Debug/netcoreapp2.0/UnityLauncher.Editor.dll -unityexecutable "%UNITY_EXECUTABLE_PATH_WINDOWS%" -projectpath ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output.log -runtests -testresults results.xml
  artifacts:
    name: "windows-test-logs"
    when: always
    paths:
      - "*.log"
      - "*.xml"
    expire_in: 1 week

#build:linux:
#  stage: build
#  allow_failure: true
#  tags:
#    - linux
#  script:
#    - dotnet ~/unity-log-wrapper/bin/Debug/netcoreapp2.0/UnityLogWrapper.dll -unityexecutable $UNITY_EXECUTABLE_PATH_LINUX -projectpath $(pwd)/ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output.log -quit
#  artifacts:
#      name: "linux-build-logs"
#      when: always
#      paths:
#        - "*.log"
#        - "*.xml"
#      expire_in: 1 week

#standalone:linux:
#  stage: standalone
#  allow_failure: true
#  tags:
#    - linux
#  script:
#    - dotnet ~/unity-log-wrapper/bin/Debug/netcoreapp2.0/UnityLogWrapper.dll -unityexecutable $UNITY_EXECUTABLE_PATH_LINUX -projectpath $(pwd)/ECSJobDemos -batchmode -buildLinuxUniversalPlayer build/linux-standalone -silentcrashes -automated -logfile output.log -quit
#  artifacts:
#      name: "linux-standalone-logs"
#      when: always
#      paths:
#        - "*.log"
#        - "*.xml"
#        - "ECSJobDemos/build/"
#      expire_in: 1 week

#test:linux:
#  stage: test
#  allow_failure: true
#  tags:
#    - linux
#  script:
#    - dotnet ~/unity-log-wrapper/bin/Debug/netcoreapp2.0/UnityLogWrapper.dll -unityexecutable $UNITY_EXECUTABLE_PATH_LINUX -projectpath $(pwd)/ECSJobDemos -batchmode -nographics -silentcrashes -automated -logfile output.log -runtests -testresults results.xml
#  artifacts:
#    name: "linux-test-logs"
#    when: always
#    paths:
#      - "*.log"
#      - "*.xml"
#    expire_in: 1 week
